# Generated by Django 4.1.7 on 2023-03-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='category',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
    ]
