# Generated by Django 4.1.7 on 2023-03-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_posts_category_remove_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
