# Generated by Django 4.1.7 on 2023-03-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_posts_category_posts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.AddField(
            model_name='posts',
            name='user_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
