# Generated by Django 4.1.7 on 2023-03-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_posts_user_posts_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='category',
        ),
        migrations.AlterField(
            model_name='posts',
            name='user_id',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
